base:
  project: EndToEndML
  random_state: 42
  target_col: quality
  test_size: 0.2

data_source:
  cloud_storage: artifacts/Data_given/winequalityN.csv

artifacts:
  artifacts_dir: artifacts
  raw_local_data_dir: artifacts/raw_local_data_dir
  raw_local_data: artifacts/raw_local_data_dir/winequality.csv
  split_data :
    processed_data_dir : artifacts/processed_data
    train_path : artifacts/processed_data/train.csv
    test_path : artifacts/processed_data/test.csv