base:
  project: EndToEndML
  random_state: 42
  target_col: TARGET
  test_size: 0.2

data_source:
  cloud_storage: artifacts/Data_given/winequalityN.csv

artifacts:
  artifacts_dir: artifacts
  raw_local_data_dir: artifacts/raw_local_data_dir
  raw_local_data: artifacts/raw_local_data_dir/winequality.csv
  split_data :
    processed_data_dir : artifacts/processed_data
    train_path : artifacts/processed_data/train.csv
    test_path : artifacts/processed_data/test.csv
  reports:
    reports_dir: artifacts/report
    params: artifacts/report/params.json
    scores: artifacts/report/scores.json
  models:
    model_dir: artifacts/saved_models
    model_path: artifacts/saved_models/model.joblib

estimators:
  ElasticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89
#      alpha: 0.9
#      l1_ratio: 0.4

webapp_model_dir: prediction_service/model/model.joblib
